import "zone.js";
import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";
import ProfileReactComponentWrapper, {
  IUser,
} from "@/components/ProfileReactComponentWrapper";

import ProfileAngularComponentWrapper from "@/components/ProfileAngularComponentWrapper";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function Home() {
  const initialUser = {
    name: "Mr Smith",
    email: "mr.smith@example.com",
  };
  const [user, setUser] = useState<IUser>(initialUser);
  const handleReactComponentEvent = (user: IUser) => {
    console.log("Log: handleReactComponentEvent", { user });
    setUser(user);
  };

  const handleAngularComponentEvent = (user: IUser) => {
    console.log("Log: handleAngularComponentEvent", { user });
    setUser({ name: "", email: "" });
  };
  return (
    <>
      <Head>
        <title>NextJS Host</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <Image
            className={styles.logo}
            src="https://nextjs.org/icons/next.svg"
            alt="Next.js logo"
            width={180}
            height={38}
            priority
          />
          <ProfileAngularComponentWrapper
            user={user}
            onAngularComponentEvent={handleAngularComponentEvent}
          />
          <ProfileReactComponentWrapper
            user={user}
            onReactComponentEvent={handleReactComponentEvent}
          />
        </main>
      </div>
    </>
  );
}
